name: lint-editorconfig
on: [push, pull_request]

jobs:
  editorconfig:
    name: Editorconfig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install requirements
      run: pip install editorconfig-checker
    - name: Run editorconfig checker
      run: |
        ec -exclude .gitmodules "\\.py$"

